### ISSUE TITLE
shows error as  NoSuchMethodError: The getter 'activeStepId' was called on null.

### ISSUE THREAD

**Issue by vuppalasivakumar** [matthew-carroll/flutter_ui_challenge_feature_discovery#3]
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following NoSuchMethodError was thrown building IconTheme(IconThemeData#a143c(color:
flutter: Color(0xff000000))):
flutter: The getter 'activeStepId' was called on null.
flutter: Receiver: null
flutter: Tried calling: activeStepId
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:46:5)
flutter: #1      FeatureDiscovery.activeStep (package:digitalfinance/customfiles/feature_discovery.dart:9:10)
flutter: #2      _DescribedFeatureOverlayState.showOverlayIfActiveStep (package:digitalfinance/customfiles/feature_discovery.dart:219:42)
flutter: #3      _DescribedFeatureOverlayState.didChangeDependencies (package:digitalfinance/customfiles/feature_discovery.dart:215:5)
flutter: #4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3767:12)
flutter: #5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
flutter: #6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
flutter: #7      Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
flutter: #8      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
flutter: #9      Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
flutter: #10     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
flutter: #11     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
flutter: #12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
flutter: #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
flutter: #14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
flutter: #15     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
flutter: #16     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
flutter: #17     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
flutter: #18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
flutter: #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
flutter: #20     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
flutter: #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
flutter: #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
flutter: #23     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
flutter: #24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
flutter: #25     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
flutter: #26     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
flutter: #27     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
flutter: #28     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
flutter: #29     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
flutter: #30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
flutter: #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
flutter: #32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
flutter: #33     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
flutter: #34     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
flutter: #35     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
flutter: #36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
flutter: #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
flutter: #38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
flutter: #39     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
flutter: #40     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
flutter: #41     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
flutter: #42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
flutter: #43     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
flutter: #44     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
flutter: #45     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
flutter: #46     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
flutter: #47     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
flutter: #48     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
flutter: #49     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
flutter: #50     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
flutter: #51     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
flutter: #52     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
flutter: #53     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
flutter: #54     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
flutter: #55     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
flutter: #56     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
flutter: #57     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
flutter: #58     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
flutter: #59     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
flutter: #60     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
flutter: #61     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
flutter: #62     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
flutter: #63     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
flutter: #64     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
flutter: #65     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
flutter: #66     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
flutter: #67     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
flutter: #68     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
flutter: #69     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
flutter: #70     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
flutter: #71     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
flutter: #72     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
flutter: #73     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
flutter: #74     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
flutter: #75     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
flutter: #76     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
flutter: #77     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
flutter: #78     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
flutter: #79     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
flutter: #80     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
flutter: #81     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
flutter: #82     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
flutter: #83     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
flutter: #84     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
flutter: #85     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
flutter: #86     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
flutter: #87     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
flutter: #88     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
flutter: #89     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
flutter: #90     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
flutter: #91     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
flutter: #92     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
flutter: #93     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
flutter: #94     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
flutter: #95     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
flutter: #96     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
flutter: #97     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
flutter: #98     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
flutter: #99     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
flutter: #100    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
flutter: #101    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
flutter: #102    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
flutter: #103    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
flutter: #104    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
flutter: #105    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
flutter: #106    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
flutter: #107    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
flutter: #108    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
flutter: #109    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
flutter: #110    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
flutter: #111    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
flutter: #112    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
flutter: #113    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
flutter: #114    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
flutter: #115    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
flutter: #116    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
flutter: #117    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
flutter: #118    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
flutter: #119    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
flutter: #120    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
flutter: #121    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
flutter: #122    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
flutter: #123    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
flutter: #124    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
flutter: #125    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
flutter: #126    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
flutter: #127    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
flutter: #128    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
flutter: #129    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
flutter: #130    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
flutter: #131    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
flutter: #132    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
flutter: #133    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
flutter: #134    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
flutter: #135    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
flutter: #136    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
flutter: #137    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
flutter: #138    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
flutter: #139    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
flutter: #140    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
flutter: #141    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
flutter: #142    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
flutter: #143    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
flutter: #144    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
flutter: #145    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
flutter: #146    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
flutter: #147    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
flutter: #148    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
flutter: #149    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
flutter: #150    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
flutter: #151    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
flutter: #152    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
flutter: #153    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
flutter: #154    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
flutter: #155    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
flutter: #156    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
flutter: #157    ParentDataElement.mount (package:flutter/src/widgets/framework.dart:3955:11)
flutter: #158    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
flutter: #159    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
flutter: #160    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
flutter: #161    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
flutter: #162    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
flutter: #163    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
flutter: #164    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
flutter: #165    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
flutter: #166    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
flutter: #167    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
flutter: #168    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
flutter: #169    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
flutter: #170    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
flutter: #171    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
flutter: #172    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
flutter: #173    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
flutter: #174    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4437:32)
flutter: #175    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4769:17)
flutter: #176    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
flutter: #177    _TheatreElement.update (package:flutter/src/widgets/overlay.dart:507:16)
flutter: #178    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
flutter: #179    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
flutter: #180    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
flutter: #181    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2242:33)
flutter: #182    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:626:20)
flutter: #183    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
flutter: #184    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
flutter: #185    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
flutter: #186    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
flutter: #187    _invoke (dart:ui/hooks.dart:120:13)
flutter: #188    _drawFrame (dart:ui/hooks.dart:109:3)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: Another exception was thrown: NoSuchMethodError: The getter 'activeStepId' was called on null.
flutter: Another exception was thrown: NoSuchMethodError: The getter 'activeStepId' was called on null.

**Comment by vuppalasivakumar** [comment]
it is working like champ but shows red screen

**Comment by ToniTornado** [comment]
Make sure you wrapped your scaffold into a FeatureDiscovery widget. See main.dart line 37.

**Comment by vinicioslc** [comment]
hi anyone can help me ? im having the issue that when i call the method discover features his trhows the follow exception... im using the fluro extension.
```
I/flutter (25189): Another exception was thrown: NoSuchMethodError: The method 'discoverFeatures' was called on null.```
