### ISSUE TITLE
NoSuchMethodError: The method 'discoverFeatures' was called on null.

### ISSUE THREAD

**Issue by anderscheow** [matthew-carroll/flutter_ui_challenge_feature_discovery#6]
Getting this error when trying to call discoverFeatures

I already wrapped Scaffold with FeatureDiscovery and DescribedFeatureOverlay is wrapping FloatingActionButton inside the Scaffold

```
NoSuchMethodError: The method 'discoverFeatures' was called on null.
Receiver: null
Tried calling: discoverFeatures(Instance(length:1) of '_GrowableList')
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      FeatureDiscovery.discoverFeatures (package:xxx/widgets/feature_discovery.dart:14:11)
#2      _LibraryContentPageState.build.<anonymous closure> (package:xxx/views/library/library_content.dart:49:18)
#3      RefreshIndicatorState._show.<anonymous closure> (package:flutter/src/material/refresh_indicator.dart:357:53)
#4      _RootZone.runUnary (dart:async/zone.dart:1379:54)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:486:5)
#9      Future<…>
```

**Comment by msilvamolina** [comment]
Hi,

I found this solution:

In  **feature_discovery.dart** :

L4-5 Replace for this:
`class FeatureDiscovery extends StatefulWidget {`
`static final featureDiscoveryKey = new GlobalKey<_FeatureDiscoveryState>();`
`static String activeStep(BuildContext context) {`

L32-36 Replace for this:
`  final Widget child;`
`  final Key key;
`
`  FeatureDiscovery({`
`    this.key,`
`    this.child,`
`  });`

In  **main.dart** :
L34 Replace:
`class _MyHomePageState extends State<MyHomePage> {`
`static final featureDiscoveryKey = FeatureDiscovery.featureDiscoveryKey;`

L37 Replace:
`return FeatureDiscovery(`
`key: featureDiscoveryKey,`

now you can call the function: 
`featureDiscoveryKey.currentState.discoverFeatures([feature1, feature2, feature3, feature4]);`

Enjoy! 👍
